[package]
name = "location"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
timeline   = { workspace = true }
anyhow     = { workspace = true }
camino     = { workspace = true }
chrono     = { workspace = true }
rusqlite   = { workspace = true }
thiserror  = { workspace = true }
