[package]
name = "activity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "activity"
path = "src/main.rs"

[dependencies]
config   = { workspace = true }
periods  = { workspace = true }
report   = { workspace = true }
timeline = { workspace = true }
miette   = { workspace = true }
camino   = { workspace = true }
chrono   = { workspace = true }
tokio    = { workspace = true }
