[package]
name        = "activity"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true
authors.workspace     = true
license.workspace     = true

[[bin]]
name = "activity"
path = "src/main.rs"

[dependencies]
config   = { workspace = true }
proto    = { workspace = true }
sources  = { workspace = true }
timeline = { workspace = true }
location = { workspace = true }
report   = { workspace = true }
anyhow            = { workspace = true }
thiserror         = { workspace = true }
miette            = { workspace = true }
clap              = { workspace = true }
camino            = { workspace = true }
chrono            = { workspace = true }
tokio             = { workspace = true }
rusqlite          = { workspace = true }
