[package]
name = "periods"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
location = { workspace = true }
sources = { workspace = true }
timeline = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
camino = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
rusqlite = { workspace = true }
